# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='conductor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cir', to='itv.conductor'),
            preserve_default=False,
        ),
    ]
