# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itv', '0006_conductor_vehiculos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='centros',
            field=models.ManyToManyField(to='itv.centros'),
        ),
    ]
