# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itv', '0007_vehiculo_centros'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='centros',
            new_name='centro',
        ),
        migrations.RenameModel(
            old_name='vehiculo',
            new_name='conductor',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='vehiculos',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='centros',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='centro',
        ),
        migrations.AddField(
            model_name='resultado',
            name='centro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='centro', to='itv.centro'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='conductor',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='centro',
            field=models.ManyToManyField(to='itv.centro'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='vehiculos',
            field=models.ManyToManyField(to='itv.vehiculo'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='vehiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='itv.vehiculo'),
            preserve_default=False,
        ),
    ]
